language: node_js
node_js:
  - '10'
  - '8'
  - '6'

notifications:
  email: false

before_deploy:
  - 'cd docs && npm install && npm run build'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/dist
  on:
    tags: true
