language: node_js
node_js:
  - node
  - '10'
  - '8'
  - '6'

jobs:
  include:
    - stage: deploy
      name: "Deploy Playground"
      node_js: node
      before_deploy: cd playground && npm install && npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: playground/build
        on:
          tags: true

notifications:
  email: false